### ISSUE TITLE
password argument might not be passed along correctly

### ISSUE THREAD

**Issue by jensim** [jensim/bitbucket_server_cli#21]
In a discussion with @sreddy31 here
https://gist.github.com/eeichinger/babbdf99d8fe21fef8634d56f29defba

It came to my attention that password passed with the --password argument might not be propagated to the reqests against bitbucket apis

**Comment by jensim** [comment]
@sreddy31 I'm sorry this issue has been been dormant for so long, I've had (and still have) more on my OSS plate than I have time for.
I added tests to see if i could pinpoint your problem here. But unfortunately I am not able to..
Might be that your password is being mangled by the terminal input, if it contains some kind of special characters?

**Comment by CumpsD** [comment]
I can reproduce on Windows. No special password. In an env var it works
