### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by elmonitoboy** [jensim/bitbucket_server_cli#4]
I didn't know a different way to ask you a question but to open an issue, so sorry if this isn't the right way to do this. Is there some pagination or limit to the number of repos and projects this pulls? I have 182 projects in my bitbucket instance, but this is only pulling 26 projects. And the user that I'm using (my user) is the top level administrator for the whole server instance

I'm running 
`bitbucket_server_cli clone-projects`

**Comment by elmonitoboy** [comment]
I'll close this issue. It must have been some strange bug, because i deleted the working directory and tried again and it worked beautifully. Thanks for this cli!!

**Comment by jensim** [comment]
Hi @elmonitoboy! Im super glad you like it =)

GH-issues works just fine =)

One thing that might have been happening to you is that, if you enter your do not enter a password, the underlying http-request-framework will handle it as a anon login http-wise. And thuss only fetch the public repos. 
Might that have been the case?
