### ISSUE TITLE
Cloning from bitbucket.org

### ISSUE THREAD

**Issue by sanders54** [jensim/bitbucket_server_cli#5]
Great tool, but I get an error when trying to download from bitbucket.org. As server address I typed https://bitbucket.org.

Error:
`Failed fetching user & project repos. Failed loading user repos due to 'Failed fetching users from bitbucket, status code: 404 Not Found.'. Failed loading project repos due to 'Failed fetching projects from bitbucket, status code: 404 Not Found.'
`
Is only on-prem bitbucket supported?

Thanks.

**Comment by jensim** [comment]
I'm glad you tried this out, however this tool is built for `bitbucket server`, not for bitbucket.org cloud solutions. Sorry, but i have no plan on supporting this, as I myself have not need for it.
This project is a bit overdesigned, and lacks some finesse in difference areas. You could get very far with a bit of scripting, as I found many people have done before me on several forum posts, when I started to pull together this tool.
